### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to read from null array

### ISSUE THREAD

**Issue by ali-roozbahani** [shodgson/uareu#7]
Please handle the exception in **UruImage**:

`Fatal Exception: java.lang.NullPointerException: Attempt to read from null array
       at asia.kanopi.fingerscan.UruImage.getImageBitmap(UruImage.java:69)
       at asia.kanopi.fingerscan.ScanFinger.sendImage(ScanFinger.java:46)
       at asia.kanopi.fingerscan.ScanFinger.run(ScanFinger.java:113)
       at java.lang.Thread.run(Thread.java:764)`

thanks

**Comment by davdavcoco** [comment]
Hi, just asking @asr1994 can u turnoff your fingerprint?...bcs i try to turnoff mine but still not work... i already open an issue tho.. 

and i want to ask too, have you ever see your fingerprint blinking red so fast and when u try to declare it again, the app just stopped working ?
